//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Clavier.rc
//
#define ID_MANIFEST                     1
#define IDCCMD_ABOUT                    3
#define IDCCMD_LANGUAGE                 4
#define IDCCMD_COPYLIST                 5
#define IDI_APP                         102
#define IDD_ABOUT                       102
#define IDD_MAIN                        105
#define IDD_KEYSTROKE                   117
#define IDI_ADD                         118
#define IDD_LANGUAGE                    118
#define IDI_DELETE                      119
#define IDD_CMDSETTINGS                 119
#define IDI_EDIT                        120
#define IDD_SENDKEYS                    120
#define IDB_DONATE                      125
#define IDM_CONTEXT                     127
#define ERR_INVALID_SHORTCUT            128
#define IDC_TARGET                      129
#define ERR_SHORTCUT_DUPLICATE          129
#define IDB_TARGET                      130
#define ERR_SAVING_INI                  130
#define ERR_LOADING_INI                 131
#define ERR_TARGET                      132
#define ASK_QUIT                        133
#define ASK_DELETE                      134
#define IDI_COMBO                       134
#define MSG_COPYLIST                    135
#define IDS_TOKENS                      256
#define IDS_COLUMNS                     257
#define IDS_LANGUAGE_CODE               258
#define IDS_CONDITIONS                  259
#define IDS_CONDITION_KEYS              260
#define IDS_INI_FILTER                  261
#define IDS_BROWSEDIR                   262
#define IDS_PROGRAMS                    263
#define IDS_TOOLTIPS                    264
#define IDS_DONATEURL                   265
#define IDS_SHOW_OPTIONS                266
#define IDCLST                          1001
#define IDCOPT_TEXT                     1006
#define IDCOPT_COMMAND                  1007
#define IDCTXT_TEXT                     1009
#define IDCTXT_COMMAND                  1012
#define IDCTXT_PROGRAMS                 1013
#define IDCCBO_SHOW                     1014
#define IDCTXT_DIRECTORY                1016
#define IDCCMD_QUIT                     1018
#define IDCLBL_ICON                     1020
#define IDCCHK_AUTOSTART                1021
#define IDCCMD_DIRECTORY                1023
#define IDCTXT                          1024
#define IDCLBL_EMAIL                    1025
#define IDCLBL_WEBSITE                  1026
#define IDCCMD_HELP                     1027
#define IDCCMD_ADD                      1030
#define IDCLST_LANGUAGE                 1030
#define IDCCMD_DELETE                   1031
#define IDCCMD_EDIT                     1032
#define IDCCBO_CAPSLOCK                 1035
#define IDCCBO_NUMLOCK                  1036
#define IDCCBO_SCROLLLOCK               1037
#define IDCTXT_DESCRIPTION              1039
#define IDCLBL_DESCRIPTION              1040
#define IDCLBL_DONATE                   1041
#define IDCFRA_TEXT                     1042
#define IDCFRA_COMMAND                  1043
#define IDCLBL_HELP                     1044
#define IDCLBL_PROGRAMS                 1047
#define IDCCMD_CMDSETTINGS              1048
#define IDCCMD_COMMAND                  1049
#define IDCIMG_PROGRAMS                 1050
#define IDCCMD_TEST                     1051
#define IDCCMD_TEXT_MENU                1054
#define IDCCHK_SUPPORTFILEOPEN          1055
#define IDCCBO_PROGRAMS                 1056
#define IDCCHK_DISTINGUISH_LEFT_RIGHT   1058
#define IDCLBL_SHORTCUTSCOUNT           1059
#define IDCTXT_SHORTCUTSCOUNT           1060
#define ID_ADD_SPECIALCHAR_FIRST        10000
#define ID_ADD_ITEM_FIRST               11000
#define ID_TEXT_SPECIALCHAR_FIRST       12000
#define ID_ADD_FOLDER                   40015
#define ID_ADD_TEXT                     40018
#define ID_ADD_COMMAND                  40019
#define ID_ADD_WEBSITE                  40020
#define ID_TEXT_SENDKEYS                40023
#define ID_TEXT_COMMAND                 40030
#define ID_TEXT_LOWLEVEL                40031
#define ID_TEXT_WAIT                    40032
#define ID_TEXT_BACKSLASH               40033
#define ID_TEXT_BRACKET_OPEN            40034
#define ID_TEXT_BRACKET_CLOSE           40035
#define ID_TEXT_BRACE_OPEN              40036
#define ID_TEXT_BRACE_CLOSE             40037
#define ID_TEXT_PIPE                    40038
#define ID_TEXT_CMD_WAIT                40039
#define ID_TEXT_CMD_FOCUS               40040
#define ID_TEXT_CMD_COPY                40041
#define ID_TEXT_CMD_MOUSE_BUTTON        40042
#define ID_TEXT_CMD_MOUSE_MOVE_TO       40043
#define ID_TEXT_CMD_MOUSE_MOVE_TO_REL   40044
#define ID_TEXT_CMD_MOUSE_MOVE_BY       40045
#define ID_TEXT_CMD_MOUSE_WHEEL         40046
#define ID_TEXT_CMD_KEYS_DOWN           40047
#define ID_TEXT_CMD_FOCUS_OR_LAUNCH     40048
#define ID_TRAY_SETTINGS                40056
#define ID_TRAY_COPY_LIST               40057
#define ID_TRAY_COPYLIST                40058
#define ID_TRAY_INI_LOAD                40059
#define ID_TRAY_INI_MERGE               40060
#define ID_TRAY_INI_SAVE                40061
#define ID_TRAY_QUIT                    40062
#define ID_UPDATE_LIST                  40063
#define ID_TRAY_INI_FIRSTFILE           41000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40067
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
